### ISSUE TITLE
如何修改框架内容？

### ISSUE THREAD

**Issue by shshsunny** [martin-liu/martin-liu.github.io#12]
请问如何修改About页面的内容，以及修改locale（将网站的语言自定义成中文）语言包？是否能直接在master分支中直接修改相关文件以达成目的？谢谢！

**Comment by martin-liu** [comment]
@shshsunny 可以自己修改对应的html文件: https://github.com/martin-liu/martin-liu.github.io/blob/staging/src/app/about/about.component.html

改完执行`./bin/deploy.sh`即可

**Comment by shshsunny** [comment]
我在npm install的时候出了这个问题：
```
gyp ERR! stack Error: Command failed: C:\Users\Sunny\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)

```
看起来是它调用Python的命令是Python 2的，与我装的Python 3不兼容，请问该怎么解决？

**Comment by martin-liu** [comment]
@shshsunny 
你可以装一个python2，然后`npm config set python /path/to/executable/python2.7`
see https://github.com/nodejs/node-gyp#on-windows

**Comment by shshsunny** [comment]
@martin-liu 搞定啦 感谢大佬
